theme: jekyll-theme-midnight
title: Migration Data
description: Get the numbers and trends right about migration in Europe and in the world. Rethink what you are told about the European migration crisis and put it into perspective with what is happening in the rest of the world. 
source: intro.html
